# Generated by Django 3.2 on 2022-01-25 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan_category',
            options={'verbose_name_plural': 'Plan_Categories'},
        ),
    ]
