# Generated by Django 3.2 on 2022-01-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='Equipment',
        ),
    ]
