# Generated by Django 3.2 on 2022-01-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_plan_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='equipment_needed',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
