# Generated by Django 3.2 on 2022-01-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
